### ISSUE TITLE
Do you record a give (by the tagger) individual ID / ‘name’ for a tagged animal (similar to our catalognumber)?

### ISSUE THREAD

**Issue by fwaumans** [lifewatch/etn-otn-exchange#1]
Jan R: We have an animal_ID, but this is linked to an external label that the fish might have, thus is not compulsory as many fish don’t have an external mark. I guess we have an animal_id_pk as well, but I leave it to Filip and Aubri to answer this.

**Comment by fwaumans** [comment]
The field `id_pk` is the primary key of the animals table. I will add this field in the geoserver layer.

**Comment by jdpye** [comment]
The pk value's a good field to have. And in cases where the researcher submits an external label for the animal, that's useful as well for disambiguating it and preparing a human-friendly component of its identification for discovery/publication later on.

**Comment by diniangela** [comment]
Can we define a field for of the primary key (id_pk) and a field for a human-defined label for the animal (in case the researchers give one)?

**Comment by fwaumans** [comment]
Sorry, I thought the field `animal_id` was already in the layer. I have added the field . Now, we have animal_id and `id_pk` in the layer. OK to close the issue?
