### ISSUE TITLE
ETN -> OTN active_deployment_network

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#10]
Column   in OTN | Example row in OTN | Equivalent in ETN
-- | -- | --
station_name | SMP123 | station_name
otn_array | SAMPLE | collectioncode
station_no | SMP123 | station_name
locality | Dalhousie University | locality
date | 2019-01-01 12:34 | deploy_date
next_proposal_date | null | null
proposal_number | null | null
otn_mission_id | SPL123 | null
intended_lat | 44.65 | stn_lat
intended_long | -63.58 | stn_long
depth_m | 123 |  depth_m
notes | Sample data | null
stationstatus | active | stationstatus

**Comment by fwaumans** [comment]
I have added the field `depth_m` in the layer ETN:stations_ETN.  I suppose the mapping is complete now?
