### ISSUE TITLE
ETN --> OTN website display

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#13]
On our website (https://members.oceantrack.org/OTN/projects), we display information about our nodes/partners.

For the map on https://members.oceantrack.org/OTN/projects, we display the average project locations for our data partners/nodes on the map and then when the user clicks it, it goes to your website (similar to the points for GLATOS) or go to an OTN-formatted web page, similar to an OTN project.      
We can also make OTN-formatted pages where there's a page but no location information (e.g. https://members.oceantrack.org/OTN/project?ccode=ACT.PROJ66) if that would be a better option for you. Which option would you prefer?

As well, we create discovery pages (https://members.oceantrack.org/OTN/data/discovery/) where users  can see information from our data partners/nodes. For example, in https://members.oceantrack.org/data/discovery/byspecies.htm, the user can see which species are in which project. Again, if they click on the project, it will go to the above selection. Is it ok to include ETN's metadata information on the discovery pages?

**Comment by jreubens** [comment]
Hi Angela, it is ok  to have the loaction information shown. Same for the discovery pages...

**Comment by diniangela** [comment]
Ok great, would you like us to build project pages similar to https://members.oceantrack.org/OTN/project?ccode=V2LNR when the points on the map are clicked (i.e. when you click on the point for V2LNR, it goes to this page) or would you like it to be directed to your website's project page, similar to if you click the point for GLATOS.GBFRM?

**Comment by jreubens** [comment]
Hi Angela, I would like to have it linking to ETN's project page

**Comment by diniangela** [comment]
Our website is up to date with the ETN data!     
You can check the main map out at https://members.oceantrack.org/ and the discovery pages out at https://members.oceantrack.org/OTN/data/discovery/

I'm going to close this issue now but feel free to reopen if you find anything off with the websites
