### ISSUE TITLE
OTN to ETN mapping project metadata

### ISSUE THREAD

**Issue by naomitress** [lifewatch/etn-otn-exchange#14]
Work on mapping the OTN to ETN project metadata fields, similar to https://github.com/lifewatch/etn-otn-exchange/blob/master/etn_otn_mappings.md 

attempt at a task list:
- [x] ETN provide full list of fields, with descriptions
- [ ] OTN provide analog where available
- [x] #15 

@diniangela

**Comment by aubrivliz** [comment]
For the imis project info we are using a standards:
- Ecological Metadata Language (EML) XML format
- Global Change Master Directory (GCMD) XML format

Example: https://www.vliz.be/en/imis?module=dataset&dasid=5884&show=eml
Info: http://www.vliz.be/en/imis?page=webservices

Do you have enough information with this to map the fields?

**Comment by diniangela** [comment]
Oh ok, yup I've previously parsed IMIS for ETN --> OTN projects
Does that mean that you want an XML for the project metadata or would the Geoserver table(s) still be fine?

**Comment by diniangela** [comment]
Also at OTN, we have a couple of tables with foreign keys to the project code, for example, to hold multiple contacts for one project, or to hold multiple species for one project.
We could share a similar format on the Geoserver layers. 
Would the following Geoserver layer format work?
- etn_projects
    - collectioncode
    - collaborationtype
    - shortname
    - longname
    - citation
    - keywords (from the GCMD you suggested)
    - abstract
    - institutioncode
    - ocean
    - country
    - state
    - local_area
    - west_boundary, east_boundary (or could be a longitude centroid)
    - south_boundary, north_boundary (or could be a latitude centroid)
    - status
    - start date and end date
    - website
- etn_contacts
    - collectioncode
    - firstname
    - lastname
    - email
    - phone number
    - address
    - affiliation (or institution they belong to)
    - website
    - orcid
    - role (role in project)
    - is_point_of_contact (showing if they are the contact or not)
- etn_species
    - collectioncode
    - scientific name
    - common name
    - aphiaid (from WoRMS)

**Comment by aubrivliz** [comment]
> Oh ok, does that mean that you want an XML for the project metadata or would the Geoserver table(s) still be fine?

Geoserver tables will be fine, thanks 👍

**Comment by CLAUMEMO** [comment]
For etn_projects I would still add the following two, that are needed for IMIS:

- Licence
- Moratorium

The rest are all complete

**Comment by diniangela** [comment]
Ok great, I will add both and add the etn_projects, etn_contacts, and etn_species layers

**Comment by diniangela** [comment]
These have been added into the OTN Geoserver layers, please let me know if they work

**Comment by aubrivliz** [comment]
@diniangela everything seems to work but for <code>otnunit:etn_projects</code> I am getting the error:

<code>
 Error occurred getting features PropertyDescriptor is null - did you request a property that does not exist? PropertyDescriptor is null - did you request a property that does not exist? 
</code>

**Comment by diniangela** [comment]
@aubrivliz Ok maybe try now

**Comment by aubrivliz** [comment]
Ok it works!

**Comment by aubrivliz** [comment]
@diniangela I will release a new version of ETN this week. 
There will be an public API available for all the metadata fields with description.

Ill post it here when i've deployed the new version.

**Comment by diniangela** [comment]
perfect, sounds good!

**Comment by aubrivliz** [comment]
@diniangela 
The metadata API is now available:

https://www.lifewatch.be/etn/ajax/dataimport/sample/{dataType}

available types:
-tag
-receiver
-deployment
-animal

Small example:

https://www.lifewatch.be/etn/ajax/dataimport/sample/tag

```json
{
	"dataType": "TAG",
	"headers": [
		"SERIAL_NUMBER",
                ....
	],
	"field_definitions": {
		"serialNumber": {
			"fieldName": "serialNumber",
			"required": true,
			"type": "string",
			"name": "SERIAL_NUMBER",
			"definition": "Serial number assigned by tag manufacturer to uniquely identify tag.",
			"unitDefinition": "as in: 1036912"
		},
              ....
	}
}

```

**Comment by diniangela** [comment]
Hey is this issue ok to close with the above changes?
