### ISSUE TITLE
OTN -> ETN missing layer fields

### ISSUE THREAD

**Issue by aubrivliz** [lifewatch/etn-otn-exchange#15]
For 2 layers we are missing fields that are mapped with ETN fields.

| otnunit:etn_animals | 
| ------------- | 
| tag_owner_pi |
| tag_manufacturer  | 

| otnunit:etn_deployments| 
| ------------- | 
| station_no|
| deploy_lat|
| deploy_long|
| ins_model_no|
| ins_serial_no|
| deployed_by|
| recover_lat|
| recover_long|
| download_date_time|
| last_download |

**Comment by diniangela** [comment]
Thank you for the list! I have now included these into the layers

I also made a list of Geoserver layers and their columns and descriptions in [OTN_geoserver_layers_and_columns.md](https://github.com/lifewatch/etn-otn-exchange/blob/master/OTN_geoserver_layers_and_columns.md)

Please let me know if these look good and work

**Comment by aubrivliz** [comment]
@diniangela On the layers i get following error:

**otnunit:etn_animals:**
<code>
java.lang.RuntimeException: java.io.IOException java.io.IOExceptionorg.postgresql.util.PSQLException: ERROR: column "type" does not exist Position: 8 ERROR: column "type" does not exist Position: 8
</code>

**otnunit:etn_deployments:**
<code>
java.lang.RuntimeException: java.io.IOException java.io.IOExceptionorg.postgresql.util.PSQLException: ERROR: column "model" does not exist Position: 33 ERROR: column "model" does not exist Position: 33
</code>

**Comment by diniangela** [comment]
@aubrivliz I changed some of the names of the fields (e.g. type --> tag_type)

It has now been fixed in the Geoserver layers

**Comment by aubrivliz** [comment]
@diniangela I've just noticed that we are missing the receiver manfacturer. Is it possible to add this in the <code>etn_deployments</code> layer?

**Comment by diniangela** [comment]
@aubrivliz Yup, I've added a "manufacturer" field into the `etn_deployments` layer and have fixed the duplicate catalognumber issue that was happening earlier 😄

**Comment by aubrivliz** [comment]
Is it possible to add the tag frequency in the latyer "otnunit:etn_animals" ?

**Comment by diniangela** [comment]
Yup, it should be in there now as `tag_frequency`
