### ISSUE TITLE
ETN-OTN cross matching process discussion

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#18]
The process for ETN and OTN cross-matching should be figured out more

One potential process (during push about 3 times a year):
- OTN pulls ETN's Geoserver layers
- OTN updates OTN's Geoserver layers (and lets ETN know)
- OTN makes a cross-match report of OTN+node tags to ETN detections (using ETN's detections layer) (tags to match, detections to un-match)
- OTN makes a cross-match report of OTN+node detections to ETN tags (using ETN's tag layer) (tags to match, detections to un-match)
- OTN shares reports with ETN
- ETN updates their database to add/remove OTN+node tags to tracker columns
- OTN updates their database (and nodes' databases) to add/remove ETN tags to their tracker columns
- OTN sends out detection extracts (reports) to their researchers

We can as well have a "code sprint" to discuss these steps

@jdpye @naomitress

**Comment by aubrivliz** [comment]
Can we plan a meeting to discuss this further?

**Comment by diniangela** [comment]
Definitely, when are you free?

**Comment by diniangela** [comment]
The decision from this meeting:
- OTN uses the ETN mystery tags layer to figure out what OTN tags could be matched to ETN detections during the push
- OTN updates OTN's Geoserver layers (and lets ETN know)
- ETN uses OTN's mystery tags layer to figure out what ETN tags could be matched to OTN detections
- OTN sends out reports to their researchers
