### ISSUE TITLE
ETN Geoserver project layer has OTN projects

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#20]
I'm parsing through the ETN project Geoserver layer and noticed that there are some projects in there e.g. V2LFALK that I believe are mirrored from OTN and are passed to ETN through the OTN European projects Geoserver layer. Is there a way to exclude these maybe in the layer so we don't accidentally include them in the database as ETN.V2LFALK along with OTN.V2LFALK?

There could also be another option to maybe put a flag on them so they are differentiable. We, at OTN, like to use the 'node.' prefix to distinguish

**Comment by aubrivliz** [comment]
The field has been added to the layer, we will update the values for the projects.
