### ISSUE TITLE
Contact differences between OTN and ETN

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#21]
Parsing through the ETN project metadata and comparing it to OTN metadata, we found some differences that might need some review:
- for https://www.lifewatch.be/en/imis?module=person&persid=38461, we have 'Mignucci, Alexander' instead of 'Minucci, Alexander'
- for https://www.lifewatch.be/en/imis?module=person&persid=38192, we have 'McGill, Ross' instead of 'MCGill, Ross' and have the email as 'ross.mcgill@loughs-agency.org' instead of 'ros.mcgill@loughs-agency.org'
- for https://www.lifewatch.be/en/imis?module=person&persid=38091,  we have the email as 'aytacozgul@gmail.com' instead of 'altan.lok@ege.edu.tr'
- for https://www.lifewatch.be/en/imis?module=person&persid=38894, we have 'Stakėnas, Saulius' instead of 'Stakenas, Saulius'

@jdpye @naomitress

**Comment by diniangela** [comment]
Also we track ORCIDs too and found some ORCIDs for the contacts:
- http://www.lifewatch.be/en/imis?module=person&persid=31255: 0000-0001-7024-3284
- http://www.lifewatch.be/en/imis?module=person&persid=37302: 0000-0001-7319-991X
- http://www.lifewatch.be/en/imis?module=person&persid=38453: 0000-0002-1938-5460
- http://www.lifewatch.be/en/imis?module=person&persid=35670: 0000-0001-8521-6270
- http://www.lifewatch.be/en/imis?module=person&persid=35736: 0000-0002-2163-0955
- http://www.lifewatch.be/en/imis?module=person&persid=221: 0000-0002-3159-5751
- http://www.lifewatch.be/en/imis?module=person&persid=229: 0000-0001-6544-9210
- http://www.lifewatch.be/en/imis?module=person&persid=8918: 0000-0002-0651-3056
- http://www.lifewatch.be/en/imis?module=person&persid=8908: 0000-0002-4437-5678
- http://www.lifewatch.be/en/imis?module=person&persid=7223: 0000-0003-2732-7428
- http://www.lifewatch.be/en/imis?module=person&persid=33411: 0000-0002-2856-8787
- http://www.lifewatch.be/en/imis?module=person&persid=37825: 0000-0001-5166-0912
- http://www.lifewatch.be/en/imis?module=person&persid=30781: 0000-0002-2610-6941
- http://www.lifewatch.be/en/imis?module=person&persid=35341: 0000-0001-8959-0884
- http://www.lifewatch.be/en/imis?module=person&persid=36837: 0000-0003-1853-3086
- http://www.lifewatch.be/en/imis?module=person&persid=38772: 0000-0002-8506-3355
- http://www.lifewatch.be/en/imis?module=person&persid=35342: 0000-0001-6670-3700
- http://www.lifewatch.be/en/imis?module=person&persid=38768: 0000-0003-1142-1372
- http://www.lifewatch.be/en/imis?module=person&persid=28147: 0000-0002-2395-454X
- http://www.lifewatch.be/en/imis?module=person&persid=35665: 0000-0002-8644-8222
- http://www.lifewatch.be/en/imis?module=person&persid=35666: 0000-0002-7632-1228
- http://www.lifewatch.be/en/imis?module=person&persid=38484: 0000-0003-3264-6167
- http://www.lifewatch.be/en/imis?module=person&persid=38091: 0000-0001-7706-9012
- http://www.lifewatch.be/en/imis?module=person&persid=36773: 0000-0001-6384-687X
- http://www.lifewatch.be/en/imis?module=person&persid=9690: 0000-0002-8451-5532
- http://www.lifewatch.be/en/imis?module=person&persid=35365: 0000-0001-8043-4324
- http://www.lifewatch.be/en/imis?module=person&persid=35661: 0000-0002-9802-8153
- http://www.lifewatch.be/en/imis?module=person&persid=38418: 0000-0001-7083-2396
- http://www.lifewatch.be/en/imis?module=person&persid=38465: 0000-0002-8888-8731
- http://www.lifewatch.be/en/imis?module=person&persid=38527: 0000-0002-4616-9296
- http://www.lifewatch.be/en/imis?module=person&persid=3466: 0000-0001-9129-9009
- http://www.lifewatch.be/en/imis?module=person&persid=226: 0000-0002-8476-1362
- http://www.lifewatch.be/en/imis?module=person&persid=38861: 0000-0003-2861-527X
- http://www.lifewatch.be/en/imis?module=person&persid=38454: 0000-0002-7373-6380
- http://www.lifewatch.be/en/imis?module=person&persid=38450: 0000-0003-3345-5426
- http://www.lifewatch.be/en/imis?module=person&persid=38416: 0000-0003-1620-5396
- http://www.lifewatch.be/en/imis?module=person&persid=38460: 0000-0002-4845-4277
- http://www.lifewatch.be/en/imis?module=person&persid=29301: 0000-0001-7149-3648
- http://www.lifewatch.be/en/imis?module=person&persid=35721: 0000-0002-5174-1197
- http://www.lifewatch.be/en/imis?module=person&persid=35735: 0000-0003-0927-6823
- http://www.lifewatch.be/en/imis?module=person&persid=35668: 0000-0002-2706-0893
- http://www.lifewatch.be/en/imis?module=person&persid=21519: 0000-0003-1084-8358
- http://www.lifewatch.be/en/imis?module=person&persid=35546: 0000-0002-4121-3817
- http://www.lifewatch.be/en/imis?module=person&persid=38915: 0000-0002-0793-2738
- http://www.lifewatch.be/en/imis?module=person&persid=39535: 0000-0001-6650-3020
- http://www.lifewatch.be/en/imis?module=person&persid=37898: 0000-0003-4346-1432
- http://www.lifewatch.be/en/imis?module=person&persid=37897: 0000-0002-6806-2406
- http://www.lifewatch.be/en/imis?module=person&persid=37902: 0000-0002-0484-1128
- http://www.lifewatch.be/en/imis?module=person&persid=37901: 0000-0003-1254-4614
- http://www.lifewatch.be/en/imis?module=person&persid=37899: 0000-0001-7531-1813
- http://www.lifewatch.be/en/imis?module=person&persid=37900: 0000-0003-3390-3292
- http://www.lifewatch.be/en/imis?module=person&persid=35679: 0000-0001-6830-4754
- http://www.lifewatch.be/en/imis?module=person&persid=20790: 0000-0002-1411-0126
- http://www.lifewatch.be/en/imis?module=person&persid=36609: 0000-0003-3741-1594
- http://www.lifewatch.be/en/imis?module=person&persid=10916: 0000-0002-0916-7363
- http://www.lifewatch.be/en/imis?module=person&persid=38421: 0000-0001-6564-0015
- http://www.lifewatch.be/en/imis?module=person&persid=38420: 0000-0002-7457-8468
- http://www.lifewatch.be/en/imis?module=person&persid=37690: 0000-0002-2185-297X
- http://www.lifewatch.be/en/imis?module=person&persid=37691: 0000-0001-5000-2918
- http://www.lifewatch.be/en/imis?module=person&persid=38413: 0000-0002-7253-2837
- http://www.lifewatch.be/en/imis?module=person&persid=39840: 0000-0003-0344-1939
- http://www.lifewatch.be/en/imis?module=person&persid=39838: 0000-0001-6804-5342
- http://www.lifewatch.be/en/imis?module=person&persid=13565: 0000-0002-5028-4983
- http://www.lifewatch.be/en/imis?module=person&persid=35686: 0000-0003-2567-4434
- http://www.lifewatch.be/en/imis?module=person&persid=35685: 0000-0002-0795-5614
- http://www.lifewatch.be/en/imis?module=person&persid=35687: 0000-0002-3843-4635
- http://www.lifewatch.be/en/imis?module=person&persid=35683: 0000-0003-2180-684X
- http://www.lifewatch.be/en/imis?module=person&persid=35799: 0000-0002-4878-7768
- http://www.lifewatch.be/en/imis?module=person&persid=35802: 0000-0002-3843-4635
- http://www.lifewatch.be/en/imis?module=person&persid=35800: 0000-0002-4549-1910
- http://www.lifewatch.be/en/imis?module=person&persid=38874: 0000-0003-4388-2093
- http://www.lifewatch.be/en/imis?module=person&persid=38093: 0000-0001-9242-0560
- http://www.lifewatch.be/en/imis?module=person&persid=38188: 0000-0002-5343-7914
- http://www.lifewatch.be/en/imis?module=person&persid=38190: 0000-0002-7100-1161
- http://www.lifewatch.be/en/imis?module=person&persid=38895: 0000-0002-1093-4750
- http://www.lifewatch.be/en/imis?module=person&persid=38191: 0000-0002-1121-638X
- http://www.lifewatch.be/en/imis?module=person&persid=35667: 0000-0003-3411-7015
- http://www.lifewatch.be/en/imis?module=person&persid=9625: 0000-0002-7983-8775
- http://www.lifewatch.be/en/imis?module=person&persid=35681: 0000-0001-5540-7148
- http://www.lifewatch.be/en/imis?module=person&persid=38097: 0000-0001-5982-482X
- http://www.lifewatch.be/en/imis?module=person&persid=38099: 0000-0001-5801-4200
- http://www.lifewatch.be/en/imis?module=person&persid=38098: 0000-0003-3807-7524
- http://www.lifewatch.be/en/imis?module=person&persid=38468: 0000-0002-4216-0315
- http://www.lifewatch.be/en/imis?module=person&persid=38879: 0000-0003-1010-0577
- http://www.lifewatch.be/en/imis?module=person&persid=38776: 0000-0002-4572-4083
- http://www.lifewatch.be/en/imis?module=person&persid=38193: 0000-0001-6574-6418

**Comment by aubrivliz** [comment]
@diniangela I will discuss this :)

**Comment by CLAUMEMO** [comment]
I have updated the IMIS records with errors.
Working on updating the IMIS records to add the ORCID info

**Comment by diniangela** [comment]
Looks like these are all fixed up so closing this ticket now
