### ISSUE TITLE
Duplicate contacts

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#27]
While reviewing OTN and partner data, we discovered duplicate contacts: https://www.lifewatch.be/en/imis?module=person&persid=35802 and https://www.lifewatch.be/en/imis?module=person&persid=35687

**Comment by bart-v** [comment]
The former record has been deleted.
Where did you find those IMIS PersonIDs?

**Comment by diniangela** [comment]
It came from parsing project metadata for http://www.lifewatch.be/en/imis?dasid=6044 and http://www.lifewatch.be/en/imis?dasid=6064 but looks like they've seen been changed to use https://www.lifewatch.be/en/imis?module=person&persid=35687
