### ISSUE TITLE
Check if API handles checking contacts by emails

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#29]
Check if the IMIS API handles checking contacts by emails
This could help catch errors such as contact duplicates (e.g. Alexandre Minucci vs Alexandre Mignucci with same email)

**Comment by bart-v** [comment]
Also contact emails change often
This is not very helpful, and search by email is currently not possible.
Think GDPR, ....etc

**Comment by aubrivliz** [comment]
At this point there is no option to automate this process. Manual comparison and reporting is needed here.
