### ISSUE TITLE
Is there a layer for the tag manufacturer and programming details (i.e. the contents of the ETN ‘tags’ table)?

### ISSUE THREAD

**Issue by fwaumans** [lifewatch/etn-otn-exchange#3]
I have added a new layer on our geoserver:
http://geo.vliz.be/geoserver/ETN/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=ETN:tags

**Comment by fwaumans** [comment]
•	Animals
o	Animal_id
•	Tags
o	Tag_id_code
o	Tag_type
o	Tag_manufacturer
o	Tag_model
o	Tag_serial_number
o	Tagger
o	Tag_owner_pi
o	Tag_owner_organization
o	Harvest_date
•	Deployments
o	Receiver_deployed_by
Can we integrate this information into the layers?

**Comment by fwaumans** [comment]
What is the meaning of the field `Tagger `and `Harverst_data`. Not sure we have this information on tag level.

**Comment by diniangela** [comment]
`tagger` is the person who tagged the animal.

`harvest_date` is used if someone finds the tag before the tag is supposed to expire

**Comment by fwaumans** [comment]
We don't have fields that store this information.

**Comment by fwaumans** [comment]
We will add the field `tagger `in the animal_tag_release table
I think `harvest_date` = recapture_date in the animal_table

**Comment by fwaumans** [comment]
The field tagger is added in the ([animals layer](http://geo.vliz.be/geoserver/wfs?service=wfs&version=2.0.0&request=GetFeature&typeNames=etn:animals&outputFormat=CSV) but is empty in most of the rows.
