### ISSUE TITLE
Harmonize mystery tag layer dataset

### ISSUE THREAD

**Issue by aubrivliz** [lifewatch/etn-otn-exchange#32]
We want to create a dataset standard for the mystery tag layer.

Proposal:

```json
        {
                "id": 1,
                "transmitter": "TBs-998825",
                "yearcollected": 2022,
                "datetimecollected": "2017-01-01T12:07:23Z",
                "region": "England South Coast",
                "collectioncode": "FISHINTEL"
        }
```
Datetime preferably ISO-8601 format (e.g. 2017-01-01T12:07:23Z)

**Comment by diniangela** [comment]
Created a new etn_mysterytags layer with this format:
- region
- datetime (in ISO-8601 format described above)
- transmitter
- datelastmodified

This layer has been added been added to the OTN Geoserver under the etn_user

I converted the datetime format to ISO-8601, but wonder would yearcollected be helpful to add to the current layer? @aubrivliz

**Comment by aubrivliz** [comment]
yearcollected is not needed, this has been resolved. 👍
