### ISSUE TITLE
How do you handle receivers that transmit (i.e. VR2-Tx units)?

### ISSUE THREAD

**Issue by fwaumans** [lifewatch/etn-otn-exchange#4]
Jan R.: I’m not sure what you mean with this question? Under receiver we have the field ‘rcv_built_in _tag’ where ID is mentioned. Under tags we have the field ‘tag_type’ where you can choose between animal, sentinel, built_in, …Under animals this id is also mentioned as species ‘built-in’ . What is the logic OTN uses?

**Comment by fwaumans** [comment]
dinaangela: For receivers that transmit, we use a transmitter column in the metadata to record the receiver’s ping code. We then treat it as a transmitter that’s not attached to an animal, like a sentinel or range test tag.

**Comment by fwaumans** [comment]
The built-in tags can be selected by the field  'acoustic_tag_type' in the layer 'ETN:tags' (value= 'built-in)'.
I have added a layer 'ETN:receivers'. In the field 'built_in_tag_fk' the id of the built-in tag is stored.

**Comment by jdpye** [comment]
Alright we'll peek at that. Is the ETN Geoserver currently down?

**Comment by fwaumans** [comment]
I did a vacuum operation on the server to recover some disk space. Maybe this causes some delay in requesting the ETN layers.
