### ISSUE TITLE
Missing properties in otnunit:etn_stations

### ISSUE THREAD

**Issue by paulfvliz** [lifewatch/etn-otn-exchange#40]
When fetching data from the otnunit:etn_stations layer we have noticed that some properties that were there in the past are no longer being delivered. 

Example request: 
[https://members.oceantrack.org/geoserver/wfs?request=getfeature&service=wfs&outputFormat=application%2Fjson&maxFeatures=10000&count=10000&startindex=0&typeName=otnunit%3Aetn_stations](https://members.oceantrack.org/geoserver/wfs?request=getfeature&service=wfs&outputFormat=application%2Fjson&maxFeatures=10000&count=10000&startindex=0&typeName=otnunit%3Aetn_stations)

List of properties 

|Supported OTN properties|Delivered OTN properties|Example Value|
|------------------------|------------------------|-------------|
|collectioncode| | |
||datelastmodified|2018-05-23Z|
|deploy_date|deploy_date|2013-04-23T18:30:00Z|
|depth_m|depth_m| null|
|downloads|downloads|5|
|instrumenttype|instrumenttype|rcvr|
|is_active_now|is_active_now|0|
|last_download|last_download|2017-02-14T16:40:01Z|
|last_recovery_date|last_recovery_date|2019-08-08T09:50:00Z|
|locality|locality| null|
|model|model| null|
|ocean|ocean|NE ATLANTIC|
|off_set|off_set| null|
|seriescode|seriescode|OTNGlobal|
|station_name| | |
|station_type|station_type|acoustic|
|stationstatus|stationstatus|active|
|stn_lat|stn_lat|38.5167|
|stn_long|stn_long|-28.6319|

As you can see the following fields are missing : 
  - collectioncode
  -  station_name

Is there a chance to make these fields available again? If not then I'll investigate the possibility of ignoring these fields during harvest.

**Comment by diniangela** [comment]
This was due to primary key setting but should now be fixed
