### ISSUE TITLE
Add an updated version of the ETN ER diagram

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#41]
Currently, there is an ETN ER diagram in https://github.com/lifewatch/etn-otn-exchange/blob/master/20161122_ETN-DB-presentation.png from 2016. It would be great to have a more up-to-date version to help with future cross-walking

**Comment by CLAUMEMO** [comment]
can you reassign the issue to [@bfur](https://github.com/bfur) (stijn)? We have a complete ERP in our documentation, but I think he wanted to make a version with only relevant columns per table

**Comment by diniangela** [comment]
Can you add him (and everyone else) to this project? He's currently not eligible to be an assignee

**Comment by bfur** [comment]
Hey if I have access I can add them to the repo. 
For now I can addthem here. 
The complete erd has some relations that are not formally set. 
![ETN_complete_erd_2024](https://github.com/lifewatch/etn-otn-exchange/assets/35014901/e2fb0f29-c8c4-468b-a671-0d4c14c38497)
![ETN_simple_erd_2024](https://github.com/lifewatch/etn-otn-exchange/assets/35014901/b298a9a2-d916-4cbd-b6e6-98fe0f140362)

**Comment by bart-v** [comment]
Hi @bfur I've sent you an invite to become member of this repo

**Comment by jdpye** [comment]
@bfur are you now able to update the diagram/close this ticket?

**Comment by jdpye** [comment]
Closed by 2b85503080575c6e398bf25518a8def39b9c7890
