### ISSUE TITLE
Contact email difference - Justas Dainys

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#42]
In OTN, we have a contact (Justas Dainys) with email 'justas.dainys@gamtc.lt' but in ETN, it looks like their email is shown as 'justas,dainys@gamtc.lt' (https://www.vliz.be/en/imis?module=person&persid=37215)

Should this be corrected in IMIS?

**Comment by CLAUMEMO** [comment]
✅Corrected in IMIS
