### ISSUE TITLE
Give ETN access to OTN processes

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#44]
Action item from meeting:

Give access to OTN processes (verification-methods and full-database-checks and ipython-utilities) to 
- [x] Claudia
- [x] Paul
- [x] Stijn
- [x] Reuben

**Comment by jdpye** [comment]
@CLAUMEMO What's Reuben's contact info?

**Comment by CLAUMEMO** [comment]
ruben.moreel@vliz.be :)
