### ISSUE TITLE
Deployment layer: can we integrate the field Receiver_deployed_by

### ISSUE THREAD

**Issue by fwaumans** [lifewatch/etn-otn-exchange#5]
What is the meaning of this field?
We know the institute which is the owner of the receiver and we know in which project the receiver is used.

**Comment by diniangela** [comment]
This field contains the name of the person who deployed the receiver.

**Comment by fwaumans** [comment]
We don't have  a field to store the name of the person who deployed the receiver.

**Comment by diniangela** [comment]
This is just some extra metadata if needed.

**Comment by diniangela** [comment]
As well, do you have any records that were recovered but not downloaded? if so, how would you record/infer this information?
In our database, we have a 'recovered' field which can have values 'y'(yes), 'n'(no), and 'l'(lost), and a 'data_downloaded' field which can have value 'y' or 'n'.

**Comment by fwaumans** [comment]
We will add a field receiver_deplyoyed_by.

In the receiver table we have a field `status`. This field can have the following values:
"Broken"
"Lost"
"Active" 
"Available"

I suppose we can infer these information on deployment level (in ETN= receiver on station during a period of time, end date= the receiver is being read and a detection file is downloaded)
When the status of a receiver is 'broken' or 'lost' the last deployment will not have an end date and will not have a detection file attached to it. We are discussing if we need also a status field on deployment level because without combining receiver status and deployment we can't make the difference between a deployment of an active receiver and a deployment of a broken/lost receiver.

Anyway, based on these fields, I can calculate the fields `recovered` and `data_downloaded` in the deployment geoserver layer. How do I map?

recovered (OTN) | Receiver status (ETN)  | deployment (ETN) |
-------------------  | -----------------------| ------------- |  
Yes			       |  | closed (end date <> NULL) + detection file attached  |
No				| ?  	| ?  |
Lost				| Broken/Lost  | open ( date <> NULL) + no detection file attached  |  

data_downloaded (OTN) | deployment (ETN) |
-------------------  | -----------------------
Yes			       | NA  |  detection file attached
No				| ?  	| no detection file attached
