### ISSUE TITLE
ETN -> OTN animals/tags

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#6]
Column   in OTN animal | OTN example row | Equivalent in ETN
-- | -- | --
animal_id | Sample | animals.animal_id
tag_type | Acoustic | tags.type
tag_manufacturer | VEMCO | tags.project
tag_model | V9-6L | tags.model
tag_serial_number | 1036912 | tags.serial_number
tag_id_code | 1450 | tags.id_code
tag_code_space | A69-1303 | animals.tag_code_space
tag_implant_type | INTERNAL | animals.implant_type
tag_implant_method | Midventral line incision, 2   sutures | animals.implant_method
tag_activation_date | 2007-03-16T00:00:00 | tags.activation_date
est_tag_life | 90 days | animals.est_tag_life
tagger | JOE RESEARCHER | animals.tagger
tag_owner_pi | JANE RESEARCHER | tags.owner_pi
tag_owner_organization | JANE AND JOE RESEARCH INSTITUTE | tags.owner_organization
common_name_e | CHINOOK | animals.common_name
scientific_name | Oncorhynchus tshawytscha | animals.scientific_name
capture_location | CLEAR CREEK, KOOSKIA NFH | animals.capture_location
capture_latitude | 46.12972 | animals.capture_latitude
capture_longitude | -115.93472 | animals.capture_longitude
wild_or_hatchery | H | animals.wild_or_hatchery
stock | DWORSHAK | animals.stock
length (m) | 0.152 | animals.length
weight (kg) | 0.045 | animals.weight
length_type | FORK | animals.length_type
length2 (m) | 0.2 | animals.length2
length2_type | WIDTH | animals.length2_type
life_stage | JUVENILE | animals.life_stage
age | 7 | animals.age
age_units | months | animals.age_units
sex | M | animals.sex
dna_sample_taken | N | animals.dna_sample_taken
treatment_type | ROR | animals.treatment_type
release_group | 1 | null
release_location | CLEAR CREEK, KOOSKIA NFH | animals.release_location
release_latitude | 46.12972 | animals.release_latitude
release_longitude | -115.93472 | animals.release_longitude
utc_release_date_time | 2007-07-05T22:15:00 | animals.utc_release_date_time
harvest_date | 2007-09-05 | animals.recapture_date
capture_depth (m) | 35 | null
temperature_change (degrees c) | 3.1 | animals.temperature_change
holding_temperature (degrees c) | 10.3 | animals.holding_temperature
preop_hold_period |   | animals.preop_holding_period
postop_hold_period |   | animals.post_op_holding_period
surgery_location | KOOSKIA NATIONAL FISH HATCHERY | animals.surgery_location
date_of_surgery | 2007-11-04T00:00:00 | animals.date_of_surgery
surgery_latitude | 46.12972 | animals.surgery_latitude
surgery_longitude | -115.93472 | animals.surgery_longitude
sedative | TRICAINE METHANESULFONATE | animals.sedative
sedative_concentration (ppm) | 20.0 | animals.sedative_concentration
anaesthetic | TRICAINE METHANESULFONATE | animals.anaesthetic
buffer | SODIUM BICARBONATE | animals.buffer
anaesthetic_concentration (ppm) | 70.0 | animals.anaesthetic_concentration
buffer_concentration_in_anaesthetic (ppm) | 140.0 | animals.buffer_concentration_in_anaesthetic
anaesthetic_concentration_in_recirculation   (ppm) | 50.0 | animals.anesthetic_concentration_in_recirculation
buffer_concentration_in_recirculation   (ppm) | 100.0 | animals.buffer_concentration_in_recirculation
dissolved_oxygen (ppm) | 9.4 | animals.dissolved_oxygen
comments | 146 FL mm; 39.04 WT g; pit tag   not attached; tight fit | animals.comments

**Comment by fwaumans** [comment]
I have added the missing fields to the animals layer on Geoserver: 
[animals layer| http://geo.vliz.be/geoserver/wfs?service=wfs&version=2.0.0&request=GetFeature&typeNames=etn:animals&outputFormat=CSV]
