### ISSUE TITLE
ETN -> OTN projects

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#7]
**otn_resources**

Column in OTN | Example row in OTN | Equivalent in ETN IMIS
-- | -- | --
collectioncode | SAMPLE | ?
seriescode | OTNGlobal | "ETN"
collaborationtype | Deployment | ?
shortname | Sample row | ?
longname | Sample row:a row of data | ['datasetrec']['StandardTitle']
citation | Doe, J. Sample Row. 2019 | ['datasetrec']['Citation']
abstract | This is a sample row. | ['datasetrec']['EngAbstract']
institutioncode | INST | ?
ocean | NW ATLANTIC | 'NE ATLANTIC'
country | CANADA | from geocoder
state | NOVA SCOTIA | from geocoder
local_area | Halifax | from marineregions.org ['preferredGazetteerName']
locality | Dalhousie University | from marineregions.org ['preferredGazetteerName']
westbl | -63.58 | from marineregions.org ['minLatitude']
eastbl | -63.53 | from marineregions.org ['maxLatitude']
southbl | 44.48 | from marineregions.org ['minLongitude']
northbl | 44.63 | from marineregions.org ['maxLongitude']
status | ongoing | ['datasetrec']['Progress']
usage |   | null
website | http://dal.ca/ | null
sdate | 2008-01-01 | ['temporal'][0]['StartDate']
edate | 2010-05-05  | ['temporal'][0]['EndDate']
node | OTN-Global | "ETN"
database | otn | "ETN"
db_location | db.oceantrack.org | "ETN"
datacentre | Ocean Tracking Network Data Centre, Halifax Canada / otndc@dal.ca | "VLIZ"

**contacts**

Column in OTN | Example row in OTN | Equivalent in ETN IMIS
-- | -- | --
contact_pk | otn123 | 'etn' + ['ownerships']['PersID']
firstname | John | ['ownerships']['Firstname']
lastname | Doe | ['ownerships']['LastName']
email | john.doe@dal.ca | ?
phone | 123-456-7890 | null
address | 123 Main Street | null
affiliation | DAL | ['ownerships']['OrigName']
ploneid | jdoe | null
website | dal.ca | null
orcid | 0123-4567-8901 | null

**contacts_projects**

Column in OTN | Example row in OTN | Equivalent in ETN IMIS
-- | -- | --
collectioncode | SAMPLE | ?
contact_pk | otn123 | 'etn' + ['ownerships']['PersID']
role | principalInvestigator | ['ownerships']['Role']
sdate | 2008-01-01 | ['temporal'][0]['StartDate']
edate | 2010-05-05  | ['temporal'][0]['EndDate']
is_point_of_contact | True | ['ownerships']['Role'] == 'Contact'

**scientificnames**

Column in OTN | Example row in OTN | Equivalent in ETN IMIS
-- | -- | --
datelastmodified | 2019-07-12 | current date
scientificname | Prionace glauca | ['taxterms']['TaxTerm']
commonname | blue shark | ...
collectioncode | SAMPLE | ?
aphiaid | 105801 | ['taxterms']['AphiaID']
tsn | 160424 | WoRMs
taxonstatus | accepted | WoRMs ['status']
authorityaccepted | (Linnaeus, 1758) | WoRMs ['valid_authority']
aphiaidaccepted | 105801 | WoRMs ['valid_AphiaID']
scientificnameaccpt | Prionace glauca | WoRMs ['scientificname']
kingdom | Animalia | WoRMs ['kingdom']
phylum | Chordata | WoRMs ['phylum']
classname | Elasmobranchii | WoRMs ['class']
ordername | Carcharhiniformes | WoRMs ['order']
family | Carcharhinidae | WoRMs ['family']
genus | Prionace | WoRMs ['genus']
subgenus | null |  WoRMs ['valid_name'] if WoRMs ['rank'] = 'subgenus', else null
species | glauca | WoRMs ['scientificname'].split(' ')[1]
subspecies | null | WoRMs ['valid_name'] if WoRMs ['rank'] = 'subspecies', else null
publication_policy | null | null
pp_description | null | null

**Comment by diniangela** [comment]
The following OTN fields are not mapped to any fields in the ETN Geoserver layers:
* citation
* abstract
* institutioncode
* ocean
* country
* state
* local_area
* locality
* status
* website

How would you like us to handle these?

For citation, if one is not provided, we usually have our program create one with the following format:   
_non_pi_lastname_, _non_pi_firstname_initial_., _pi_lastname_, _pi_firstname_initial_. _startyear_ _project_longname_

**Comment by fwaumans** [comment]
We describe projects and datasets in an other datasystem: IMIS  ([http://www.vliz.be/en/integrated-marine-information-system]) . This is an example of a full description of an ETN project: [http://www.vliz.be/nl/imis?module=dataset&dasid=5858].  We store the IMIS id in the project table in the ETN database.  In that way I can combine both datasources.

How do I deal with one to many relationships. Ex:
- more then one institute is involved in a project
- the project is situated in more then one country
-...

**Comment by diniangela** [comment]
Our discovery data is configured to grab from one Geoserver layer. Can you make one Geoserver layer that is a combination of the two databases?

We handle the project being situated in more than one country by having a comma between the countries in the country field, e.g. CANADA, USA. We have not seen any cases of multiple institutes for one project but assume it would be handled in a similar way.

**Comment by fwaumans** [comment]
This information of datasests/projects is also reachable by webservice: [http://www.lifewatch.be/en/imis?page=webservices]. 
i.e. dataset: [http://www.lifewatch.be/en/imis?dasid=5843&show=json]
i.e. person Jan Reubens: [http://www.lifewatch.be/en/imis?persid=14823&show=json]

I think the mapping you propose is difficult to achieve for us because we have many possible one-to-many relationships: 
- geographical coverage
- contributes (from different institutes)
- taxa

I propose to provide a link to the according webservice entry in the geoserverlayer because that will give you the most detailed and up-to- date information.

**Comment by fwaumans** [comment]
I have added the missing fields in the [project layer](http://geo.vliz.be/geoserver/wfs?service=wfs&version=2.0.0&request=GetFeature&typeNames=ETN:projects&outputFormat=CSV). Two important remarks:
1. For the one to many relationships (geographical coverage, institutes), I have added the webservice call to IMIS. In the JSON file the ownership (institutes) and geographical entries are important.
2. We have to replace the scientific names by Aphiaid.
3. We have to complement the link between the ETN database and IMIS and we have to complement the IMIS records of ETN projects.

So, this is a temporary result. 

Do you think the final completed layer will be feasible for you?

**Comment by diniangela** [comment]
We have one-to-many relationships shown in our database between projects and contacts, and projects and species. To do this, we use 4 tables: 
*  otn_resources (which holds project information)
* contacts (which holds information about each contact)
* contacts_projects (which holds information about the contacts-projects mapping)
* scientificnames (which holds information about the species and their mapping to the projects)

These tables have the following format:

**otn_resources:**

Column | Example row
--|--
collectioncode | SAMPLE
seriescode | OTNGlobal
collaborationtype | Deployment
shortname | Sample project
longname | This is a sample project
citaton | Doe, J. Sample Row. 2019
abstract | This is a sample row.
institutioncode | INST
ocean | NW ATLANTIC
country | CANADA
state | NOVA SCOTIA
local_area | Halifax
locality | Dalhousie University
westbl | -63.58
eastbl | -63.53
southbl | 44.48
northbl | 44.63
status | ongoing
usage | null
website | http://dal.ca/
sdate | 2008-01-01
edate | 2010-05-05
node | OTN-Global
database | otn
db_location | db.oceantrack.org
datacentre | Ocean Tracking Network Data Centre, Halifax Canada / otndc@dal.ca

**contacts**

Column | Example row
-- | --
contact_pk | otn123 (unique identifier that links row to contacts_projects table)
firstname | John
lastname | Doe
email | john.doe@dal.ca
phone | 123-456-7890
address | 123 Main Street
affiliation | DAL
ploneid | jdoe
website | dal.ca
orcid | 0123-4567-8901

**contacts_projects**

Column | Example row
-- | --
collectioncode | SAMPLE (links contact to project)
contact_pk | otn123 (links row to contacts table)
role | principalInvestigator
startdate | 2008-01-01
enddate | 2010-05-05
is_point_of_contact | true

**scientificnames**

Column | Example row
-- | --
datelastmodified | current_date
scientificname | Prionace glauca
commonname | blue shark
collectioncode | SAMPLE (links species to project)
aphiaid | 105801
tsn | 160424
taxonstatus | accepted
authorityaccepted | (Linnaeus, 1758)
aphiaidaccepted | 105801
scientificnameaccpt | Prionace glauca
kingdom | Animalia
phylum | Chordata
classname | Elasmobranchii
ordername | Carcharhiniformes
family | Carcharhinidae
genus | Prionace
subgenus | null
species | glauca
subspecies | null
publication_policy | null
pp_description | null

The scientificnames table mapping will help with the multiple taxa per project by having a row for each species per project, and the contacts and contacts_projects table mapping can help with multiple contacts per project (from different institutes if needed).   
To show multiple geographic regions per project, we put a comma in the country, local_area, or locality columns. For example, we have some projects that have 'CANADA, USA' as their country in the otn_resources table.   

There can also be the link to the according webservice entry in IMIS in the otn_resources table.

If this looks good, I will change the above mappings.   
As well, if this looks good, it would be a good idea to have 4 Geoserver layers to map to these tables.

**Comment by diniangela** [comment]
@fwaumans 

I have looked into how to map some of the fields from the IMIS JSON files to the OTN project tables but have a couple of questions:
1. In the projects geoserver layer, how did you calculate the following fields?
    * projectcode (or collectioncode)
    * type (or collaborationtype, e.g. network or animal)
    * shortname
2. How do you store the current projects' ids?

**Comment by Tjess** [comment]
There are some questions from the ETN workshop group as to how far we are in the process of getting the ETN -> OTN exchange and the OTN-> ETN exchange going.
Can we get an update on that please?

**Comment by fwaumans** [comment]
1.
Projectcode = shortname. 
Projectcode, Full name and type (animal or network) are required fields of a project. These fields are completed in the ETN database during the creating of a new project. The project is described in our IMIS datasystem and an IMIS id is stored in the ETN project database table as a link between ETN and IMIS.

Is this a sufficient answer to your question?

2.
What do you mean? I don't understand the question

**Comment by fwaumans** [comment]
About the OTN - project tables: we can use them to import OTN project data in our IMIS system, no problem. 

> it would be a good idea to have 4 Geoserver layers to map to these tables.
Ok, this is a good point for our meeting. We can work together on a script to extract data from the IMIS webservice into the 4 tables you need in OTN.

**Comment by diniangela** [comment]
Where would be the best place to get the project's geographical data?

I started looking at the GeoObjectID in the geographical section of the IMIS JSON and then entering that into http://marineregions.org/mrgid/GeoObjectID but sometimes this GeoObjectID is not filled in. I notice a couple of geographical IDs in the IMIS JSON but am not sure what websites they point to (e.g. DasGeoID, DasID, GeotID)

**Comment by diniangela** [comment]
Also, would you be available for a Skype meeting to help work on the script to extract the data from IMIS?

**Comment by fwaumans** [comment]
The GeoObjectID is the most important one. You can use the MarineRegions webservices to get more information on the GeoObjectID. E.g: [](http://www.marineregions.org/rest/getGazetteerRecordByMRGID.json/3293/). See also [](http://www.marineregions.org/gazetteer.php?p=webservices).
Can you give us a list of datasets with missing GeoOjbectIDs? We have to complete them.

**Comment by fwaumans** [comment]
For the Skype meeting: I am available on December  3, 4, 5 and 10, 11, 12  at 10 am local time in Halifax. When are you available?

**Comment by diniangela** [comment]
Ok, the ones without GeoObjectIDs are:

projectcode | website
--|--
BPNS | http://www.lifewatch.be/en/imis?dasid=5843&show=json
Thorntonbank | http://www.lifewatch.be/en/imis?dasid=5847&show=json
PC4C | http://www.lifewatch.be/en/imis?dasid=5848&show=json
2014 Demer | http://www.lifewatch.be/en/imis?dasid=5871&show=json
2015 Dijle | http://www.lifewatch.be/en/imis?dasid=5872&show=json
Demer | http://www.lifewatch.be/en/imis?dasid=5879&show=json
Dijle | http://www.lifewatch.be/en/imis?dasid=5880&show=json
Deveron 2016 | http://www.lifewatch.be/en/imis?dasid=5913&show=json
Moray Firth 2016 | http://www.lifewatch.be/en/imis?dasid=5914&show=json
Aberdeen 2017 | http://www.lifewatch.be/en/imis?dasid=5915&show=json
Conon 2017 | http://www.lifewatch.be/en/imis?dasid=5916&show=json
Skye 2017 | http://www.lifewatch.be/en/imis?dasid=5917&show=json
Limfjord | http://www.lifewatch.be/en/imis?dasid=5926&show=json
SVNL-FISH-WATCH | http://www.lifewatch.be/en/imis?dasid=5927&show=json
BECORV | http://www.lifewatch.be/en/imis?dasid=5928&show=json
Inforbiomares | http://www.lifewatch.be/en/imis?dasid=5929&show=json
ARAISOLA02 | http://www.lifewatch.be/en/imis?dasid=5931&show=json
ARAISOLA03 | http://www.lifewatch.be/en/imis?dasid=5932&show=json
SARTELARAM | http://www.lifewatch.be/en/imis?dasid=5933&show=json
SARTELZINGARO | http://www.lifewatch.be/en/imis?dasid=5934&show=json
SARTELTG | http://www.lifewatch.be/en/imis?dasid=5935&show=json
PTN-Silver eel-Mondego | http://www.lifewatch.be/en/imis?dasid=5936&show=json
DTU-Skjern | http://www.lifewatch.be/en/imis?dasid=5946&show=json
PTN/PROTECT2012 | http://www.lifewatch.be/en/imis?dasid=6044&show=json
Unlocking the Severn | http://www.lifewatch.be/en/imis?dasid=6052&show=json
MBA_Whitsand | http://www.lifewatch.be/en/imis?dasid=6053&show=json
MBA_Wavehub | http://www.lifewatch.be/en/imis?dasid=6054&show=json
MBA_Massmo | http://www.lifewatch.be/en/imis?dasid=6055&show=json
Eel migration from source to sea | http://www.lifewatch.be/en/imis?dasid=6057&show=json
Albertkanaal_VPS_Ham | http://www.lifewatch.be/en/imis?dasid=6058&show=json
PTN/PROTECT2013 | http://www.lifewatch.be/en/imis?dasid=6064&show=json

**Comment by diniangela** [comment]
Next week, we are going to Florida to work with FACT. 
But I should be available on the 10th, 11th, and 12th at 10 am Halifax time

**Comment by fwaumans** [comment]
@jreubens : Jan, is it possible to complete the Geobojectids in the ETN datasets in IMIS?

**Comment by fwaumans** [comment]
OK, We plan the meeting on 10th at 10am local time Halifax (15 pm in Ostend)

**Comment by diniangela** [comment]
Ok sounds good

**Comment by diniangela** [comment]
@fwaumans what is the email(s) or username(s) I should use to connect you to skype?

**Comment by fwaumans** [comment]
flanders.marine.institute

**Comment by LennertSchepers** [comment]
> 
> 
> @jreubens : Jan, is it possible to complete the Geobojectids in the ETN datasets in IMIS?

@fwaumans, currently not all 'Geoterms' in imis are linked to a MarineRegions GeoObject/MRGID. This is why some GeoTerms don't have a corresponding MRGID. Currently this mapping and linking is foreseen for spring/early summer. Do you need it earlier? See our internal VLIZ issue IMIS-852.

**Comment by fwaumans** [comment]
All projects listed in [](https://github.com/lifewatch/etn-otn-exchange/issues/7#issuecomment-559081825) have at least one GeoObjectID.

**Comment by fwaumans** [comment]
I have recreated the ETN:OTN_projects Geoserver layer. I have deleted some fields whose content came from the IMIS database. it is better to get that information from the imis web service. In the fields 'imis_projectid' and 'imis_persid_PI' you will find the URI (json) for data about the project and data about the PI of the project:

| field     | json persid PI                         |               |
|-----------|----------------------------------------|---------------|
| firstname | personrec->Firstname                   |               |
| lastname  | personrec->Surname                     |               |
| email     | insitutes[0]->instituterec->Email      |               |
| phone     | insitutes[0]->instituterec->Phone      |               |
| address   | insitutes[0]->instituterec->EncAddress |               |
| orcid     | urls->[X]->URL                         | URLType=ORCID |

| field            | json projectid_imis       |
|------------------|---------------------------|
| longname         | datasetrec->StandardTitle |
| project_citation | datasetrec->Citation      |
| project_abstract | datasetrec->EngAbstract   |
| project_status   | datasetrec->Progress      |
| startdate        | temporal->Startdate       |
| enddate          | temporal->Enddate         |

**Comment by diniangela** [comment]
Ok great!

I was looking through some of the ETN:OTN_projects and see there are some IMIS urls that are blank (e.g. Homarus) and some where it has an imis_projectid but the JSON from this link is blank (e.g. http://www.lifewatch.be/en/imis?dasid=6335&show=json for 2017_Fremur).        
Should I exclude these for now?

**Comment by diniangela** [comment]
The full list is:

projectcode | imis_project_id | JSON
--|--|--
2017_Fremur | http://www.lifewatch.be/en/imis?dasid=6335&show=json | blank
2019_Grotenete | http://www.lifewatch.be/en/imis?dasid=6337&show=json | blank
Delfzijl 2014-2015 | http://www.lifewatch.be/en/imis?dasid=6331&show=json | blank
Eemskanaal I | http://www.lifewatch.be/en/imis?dasid=6325&show=json | blank
Eemskanaal II | http://www.lifewatch.be/en/imis?dasid=6326&show=json | blank
Eemskanaal III | http://www.lifewatch.be/en/imis?dasid=6327&show=json | blank
Friesland 2011-2012 | http://www.lifewatch.be/en/imis?dasid=6328&show=json | blank
Homarus | null | NA
Iller | http://www.lifewatch.be/en/imis?dasid=6059&show=json | blank
Jersey Coastal Fish Tracking | null | NA
Kornwerderzand | http://www.lifewatch.be/en/imis?dasid=6330&show=json | blank
Lauwersmeer | http://www.lifewatch.be/en/imis?dasid=6329&show=json | blank
Lifewatch | null | NA
Maas | null | NA
MEPNSW | http://www.lifewatch.be/en/imis?dasid=6324&show=json | blank
Mobula Imar | null | NA
Ocean Tracking Network | null | NA
PhD Barbara Koeck | null | NA
PhD Jeremy Pastor | null | NA
PhysFish | null | NA
Siganid_East_Med | null | NA
Siganid_Gulf_Aqaba | null | NA
TeRi | http://www.lifewatch.be/en/imis?dasid=6292&show=json | blank

**Comment by fwaumans** [comment]
Concerning the GeoObjectID: I have added the field `mrgid` in the project layer. You can use this field instead of the geoobjectid from the IMIS json. This will be easier for you.

**Comment by fwaumans** [comment]
Concerning the `imis_project_id`:
What do you mean with blank? I get a json file when I follow the link.
Can you exclude the projects without `imis_project_id` for now?
@jreubens : Can you add a IMIS record for these projects?

**Comment by diniangela** [comment]
Great about the mrgid field! 

For the blank imis_project_id, for example, if I open 'http://www.lifewatch.be/en/imis?dasid=6324&show=json', I get a blank screen and when I try to move it into python and use requests.JSON on it, it returns an empty string. When I go to the non-JSON url 'http://www.lifewatch.be/en/imis?dasid=6324', I then get a message on IMIS that says "This record is not available"

**Comment by fwaumans** [comment]
Now I understand. These project records are not public. I can see them internally. I figure out the reason for this.

**Comment by fwaumans** [comment]
The blank json links are now visible.

**Comment by diniangela** [comment]
Ok great, I think this can be closed then. I made a new issue though about how you would like the ETN data to be displayed on our website: https://github.com/lifewatch/etn-otn-exchange/issues/13

Please let me know your preferences
