### ISSUE TITLE
ETN -> OTN mystery_tags

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#8]
Column in   OTN | Example row in OTN | Equivalent in ETN
-- | -- | --
region | NW ATLANTIC |  
collectioncode | SAMPLE |  
yearcollected | 2019 | year
fieldnumber | A69-1303-12345 | transmitter
det_count | 100 | count
seriescode | OTN-Global | "ETN"

**Comment by fwaumans** [comment]
What is the meaning of the field `collectioncode`?

**Comment by diniangela** [comment]
`collectioncode` is the project shortcode which usually consists of 3-6 uppercase letters.

**Comment by diniangela** [comment]
We, for now, will not map mystery tags because they are a data product that is made after data loading/processing is done.  

If this should be mapped in the future, we can reopen this issue
